

spring:
  datasource:
    url: jdbc:postgresql://${HOST}:${PORT}/${DATABASENAME}
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

RL:
  app:
    jwtSecret: ${SECRETKEY}
    jwtExpirationMs: ${EXPIRATIONTIME}


logging:
 file:
  name: READLIBRARY_prod.log
 pattern:
    file: "%d %-5level [%thread] %logger:%msg%n"
 
 level:
   '[org.springframework.web]': INFO
   '[org.hibernate]': INFO
   '[com.greenrent]': INFO


management:
 endpoints:
  web:
   exposure:
    include: ['info','health']
 
 info:
  env:
   enabled: true 