server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never

file:
  uploaddir: 'C:\Users\pc\IdeaProjects\Read_Library\images'


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/read_library
    username: library
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update


servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

logging:
  file:
    name: RL.log
  pattern:
    file: "%d %-5level [%thread] %logger:%msg%n"

  level:
    '[org.springframework.web]': INFO
    '[org.hibernate]': INFO
    '[com.greenrent]': DEBUG



RL:
  app:
    jwtSecret: readlibrary@55
    jwtExpirationMs: 86400000



info:
  application:
    name: 'readlibrary Backend App'
    descprition: 'This is Read Library Backend app dev by Artofcoding Dev Team'
    version: '@project.version@'


